# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ubwRBahbYbQoX8E+0Ifxve/t6/neMdhywF5OONgCf+ziKGc3H6GuN/UvFV6/PfQzp0woQnN/jkfStTsQn02JreTj2R6X76W/xnisRg50B12dkixAaX0Aj+sX6QfxYu6G0iOjcKDPf0CWz3By35q8RMznkYxeyDhkxMsof4mngObTkUH4DMbC8Pl8WpJY6/pHSNsa8sfGhWthOlH6FCKOE17w9aN20oLmxKvnBoWPtt7mWom/bGq0XJwfoqX70vq4ei5E3DEiVawXCrrUagaJPfOSF3ZmO9QhrLwA1eJjvAPfvyqEzQ8hBB7jOlXMLadNwWeRexNm8Ao5f27X4D+z+NmKH8aMtwra5n5QMoD57Y/cmEvMK1aPfY/ksDFCMdGJ7TafsuVDbxo80vayaI4iBjZgKK+s7KpyyRzWB+E/Q+6c8/qK9vHlX/ktTt9KVQkozft5dvP4QXljQMwQ9UlefbUsFdBZ02jIyU0ddbW5vjBO1KkbwYiHo0viCxw31y+nR2Yfs3i7SaV54eHjUai6C37VdDkBurejjGdzCJZ4S7Z7BzY5sP13/GfeML+pYo3xTVyIhi7txmPTBQPH3nOCnnbhKvMiBVkZrxSOmpiA08pP/ICtuwy9dEHVl2xNuJWr94wJ605uUH7P/OgGgQaM72nEmpnfn5fy1pdY+XozeDE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
