travis:
  secure:
    BINSTAR_TOKEN: huabGv4LOxHE8zL2MV4beCCGMERpF7tGGrrh8+ou25etq/R6xF2mw8Dd7cyHiUCSq9v9KPwn+Vnywh5vfQJOe0Jh9V4Y5O4pVXNZYCynYAyW+ByaG/2EOlp8MMVL4pLsu7abkTG4jkyb2CmVsYQLuiPOCbh6/SQla2jN2y/25MwhJlTL98yUIcedPxtfbiZ5GPGynJhS5M4leKql3chqNe15tHISImROFWJCnndl23xiNyfxsugylwM9QO/fyelLq5PBBcOK2Td9l9yHiZbtPPHpCkc2gvxSEafQq5lXmHAAGVrQp44TIF+Jv3o4ws7RPMp27KG5xnTs7Wd1+rQznzJHUtQhDYFfvP8Mit4aQmb+ig+uzvNRgfo1glpJMvO/kQZmFcKVLEoQBdjmnwsMj0X7MIXhX4sa4QPZ6om77QDahgZX6Up4H+4mZ+xg/Ya6VJ/JzhlDNg1JHBSxqlMyhAKM53ODvPU6RUzBidS1zx/WRtx8atXkzfVzjB/JpqxUU8qu1jHbS3CgdlOnklxHinrTOaWAtMm8SwixC3wSn6sRZLmJBv39LKZIjxRoFGg73J51g94t1DvYbFQYTnT10VNl0uhU8BlilcZENjoqglmgD0jZJJpJienQT33dbSxBheP+8vjK5OUkAAyqf2W5bPKL857UC2qyPpibkhJMu0U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
