travis:
  secure:
    BINSTAR_TOKEN: ubwRBahbYbQoX8E+0Ifxve/t6/neMdhywF5OONgCf+ziKGc3H6GuN/UvFV6/PfQzp0woQnN/jkfStTsQn02JreTj2R6X76W/xnisRg50B12dkixAaX0Aj+sX6QfxYu6G0iOjcKDPf0CWz3By35q8RMznkYxeyDhkxMsof4mngObTkUH4DMbC8Pl8WpJY6/pHSNsa8sfGhWthOlH6FCKOE17w9aN20oLmxKvnBoWPtt7mWom/bGq0XJwfoqX70vq4ei5E3DEiVawXCrrUagaJPfOSF3ZmO9QhrLwA1eJjvAPfvyqEzQ8hBB7jOlXMLadNwWeRexNm8Ao5f27X4D+z+NmKH8aMtwra5n5QMoD57Y/cmEvMK1aPfY/ksDFCMdGJ7TafsuVDbxo80vayaI4iBjZgKK+s7KpyyRzWB+E/Q+6c8/qK9vHlX/ktTt9KVQkozft5dvP4QXljQMwQ9UlefbUsFdBZ02jIyU0ddbW5vjBO1KkbwYiHo0viCxw31y+nR2Yfs3i7SaV54eHjUai6C37VdDkBurejjGdzCJZ4S7Z7BzY5sP13/GfeML+pYo3xTVyIhi7txmPTBQPH3nOCnnbhKvMiBVkZrxSOmpiA08pP/ICtuwy9dEHVl2xNuJWr94wJ605uUH7P/OgGgQaM72nEmpnfn5fy1pdY+XozeDE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
