travis:
  secure:
    BINSTAR_TOKEN: rarA2rjcOfc39KgQUehoYeTJvU+XPmT5sXz8oRjYOHTLze89goq9QnKULgATr6s8lKodeDRnnJqpxr11r9XtP29pey5ma/xsr1ML6skx6JLvwlREZIddOdt5WIp5P97tv0vpCrsbOvG2piPJdccDqVF86kBdbXkenlTGBZTnp8roDUumkG0u5bc4iLRAzXZXJPMpK2+3GFicdwCIW/m3vJEnf9y6qCiBINNZRDufaUXKYgJ2aCb42hxbJ32WtLFFiZhH8E6Pbh00nnqgxGqgYzAFi6aR1Sk1CD+bIRHApkwJae2xdzq2tKZCT5MbwSMDPkg6ZKulpDyK0/rXoTE8rIdtvxjGv4ypdUd4NUGL6igJg42IWAn8Fu+OA7KlhPMb7pZZBwCwfIw2yVRh64Jqz1eX2BgjNNRkigcYI6KU6+fx+x0ijRz6q8gF/bUeNim8Tu7DkjkCiKgeQ+UPKku1ECW+JxqbhMV6e0qHpBf5DRGCFzKNCNLf/UZcuug8GzSYWg2UaM3BTt4ufdk28XKzrKHc/KiXD0OleyoUvZtsdnctBgJ1iv/vtbcLugrqqF/GAWRy2VIBc9t0qnGjBHxq/tF8CY1iOkdnavpYdqhQKfp4oytYvUIvu8pAyWlx+FtAtqPepoH2WOQry3WUY5LUNPp9V8bk3FX5swdbeOhN/S8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
